#!/bin/bash
# ============================================================
# setup_imu_udev.sh
# 为四个 CH343 USB 转串口 IMU 分配固定设备名:
#   /dev/imu0 ~ /dev/imu3
# 按 USB 物理端口路径(ID_PATH)排序, 插拔/重启后设备名不变,
# 保证每个 IMU 始终对应同一个设备节点。
#
# 用法:
#   1. 先把四个 IMU 全部插入电脑(任意顺序)
#   2. sudo bash setup_imu_udev.sh
#   3. 脚本会打印 设备名 <-> USB端口 对应关系, 请确认
#   4. 重新插拔设备(或重启)后生效
# ============================================================

set -e

RULES_FILE="/etc/udev/rules.d/99-imu.rules"
VID="1a86"   # CH343/CH340 的 USB Vendor ID (CH343 常见 1a86:55d4)

echo "==== 扫描 USB 串口设备 ===="

# 收集所有 CH343 串口设备: <设备节点>|<ID_PATH>
declare -a DEVICES
for dev in /dev/ttyUSB*; do
    [ -e "$dev" ] || continue
    vpid=$(udevadm info -q property -n "$dev" | grep '^ID_VENDOR_ID=' | cut -d= -f2)
    if [ "$vpid" = "$VID" ] || [ "$vpid" = "1a86" ]; then
        idpath=$(udevadm info -q property -n "$dev" | grep '^ID_PATH=' | cut -d= -f2)
        DEVICES+=("$dev|$idpath")
    fi
done

if [ ${#DEVICES[@]} -eq 0 ]; then
    echo "错误: 未检测到任何 CH343 USB 串口设备 (/dev/ttyUSB*)"
    echo "请先插入 IMU 后再运行本脚本。"
    exit 1
fi

echo "检测到 ${#DEVICES[@]} 个 CH343 设备:"
for d in "${DEVICES[@]}"; do
    echo "  $d"
done

# 按 ID_PATH 排序, 保证分配顺序稳定
IFS=$'\n' SORTED=($(printf '%s\n' "${DEVICES[@]}" | sort -k2 -t'|'))

# 生成规则
echo ""
echo "==== 生成 udev 规则: $RULES_FILE ===="
{
    echo "# Auto-generated by setup_imu_udev.sh ($(date '+%Y-%m-%d %H:%M:%S'))"
    echo "# CH343 USB-TO-UART IMU fixed device names"
    idx=0
    for d in "${SORTED[@]}"; do
        dev="${d%%|*}"
        idpath="${d#*|}"
        echo "# $dev -> USB port: $idpath"
        echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$VID\", ENV{ID_PATH}==\"$idpath\", SYMLINK+=\"imu$idx\", MODE=\"0666\""
        idx=$((idx+1))
    done
} | sudo tee "$RULES_FILE" > /dev/null

echo ""
echo "==== 对应关系 (请核对物理接线) ===="
idx=0
for d in "${SORTED[@]}"; do
    dev="${d%%|*}"
    idpath="${d#*|}"
    echo "  /dev/imu$idx  <->  $dev  (USB端口: $idpath)"
    idx=$((idx+1))
done

echo ""
echo "重新加载 udev 规则..."
sudo udevadm control --reload-rules
sudo udevadm trigger --attr-match=subsystem=tty

echo ""
echo "完成! 检查固定设备名:"
sleep 1
ls -l /dev/imu*
